### ISSUE TITLE
pkgs.lock支持正则表达式匹配

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-repo/apt-repo-action#3]
https://github.com/radxa-repo/apt-repo-action/blob/main/Program.cs#L243

目前程序只支持完全匹配，但我们目前由于需要同时维护Debian 11和Debian 12两个不同的源，需要用正则表达式将两个源pin到不同的版本上
首先尝试直接全文匹配tag。若失败，则假定为正则表达式，将所有正式release的tag通过正则筛选后排序选择最新的版本。

## 示例

* `^0\.3\.`: 匹配`0.3.`开头的所有版本，用于Debian 11
* `^0\.[4-9]\.`: 匹配`0.3.`到`0.9.`开头的所有版本，用于Debian 12
* 排序需要支持semantic versioning，也即`0.11`比`0.2`版本号要新，而不能是简单的字符串比较

**Comment by CodeChenL** [comment]
暂时无此需求
